#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring:
  security:
    enabled: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
server:
    port: 8080
    servlet:
      context-path: /journals

logging:
  level:
   net:
   engineeringdigest:
    journalApp: DEBUG

weather:
  api:
    key: ${WEATHER_API_KEY}


#spring.data.mongodb.username=username
#spring.data.mongodb.password=pwd